// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d15e39bc-f95e-4ef8-bc49-49fbeb66f5c8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ABwFhdwbo",
    "aws_user_pools_web_client_id": "7jehbu9utiusolfr92u9gmboqd",
    "aws_user_files_s3_bucket": "picinterpreter3b990ca2d6a3479093294b2a22c5d994",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "rekognize",
            "endpoint": "https://sg2d41dhxe.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
